### ISSUE TITLE
Create tests for VirtoCommerce.com

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-content#7]
As a manager, I want to be sure that VirtoCommerce works as expected after update

### Acceptance criteria
- GIVEN  VirtoCommerce store
WHEN I start E2E test
THEN I should get health status of Staging and production environment.

### Definition of Done
- [x] Created E2E tests for Staging
- [x] Created E2E tests for Production
- [x] Created manual check list if we can not create automatic tests
- [x] All E2E tests should check Mobile, Tablet and Desktop mode
- [x] All E2E tests should check modern browsers

### Tasks
- [x] Create E2E test for Contact Us Forms (Post with demo data and 200 status) 
- [x] Create E2E test for redirects
- [x] Check robots.txt on Production - content and 200. 
- [x] Check robots.txt on Staging. We should use disallow for staging environment.
- [x] Check sitemap - content and 200
- [x] Check 404 and 500 pages uses 404 and 500 http status
- [x] Control degradation of response and page view times 
- [x] Check SEO Meta-information on specific pages
- [x] Control degradation of Google PageSpeed Insights score
- [x] Check Blades constructor page -> 200 status 
- [x] Check Style guide page -> 200 status

**Comment by vkrashenko** [comment]
[vccom health manual check list.docx](https://github.com/VirtoCommerce/vc-content/files/1585880/vccom.health.manual.check.list.docx)
